# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ba63219bb7787f766e4b38a19208cc9ece75e2641df42d071ebed796a4f07b124e6479e693979db513f86c795b47c139befd4c2d56701db22d79b9ceb8efecd

test:
  secret_key_base: c02c0ec6a51dc9137bb918c558d812523d76676112c242bafa9f59e91ce15bfb276979f84326e190726965e33e296da6bd88fe3b5def82b3b8611ede68aea32e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
